services:
  apache:
    build: apache-php-lamp
    ports:
      - "80:80"
      - "443:443"
    env_file:
        - .env.prod     
    volumes:
      - ./joomla:/app
      - ./apache-php-lamp/vhost-apache.conf:/etc/apache2/sites-enabled/vhost-apache.conf
      - ./apache-php-lamp/php.ini:/etc/php/8.2/apache2/php.ini
      - ./certs:/certs
