services:
  apache:
    build: apache-php-lamp
    ports:
      - "80:80"
      - "443:443"
    env_file:
        - .env.dev      
    volumes:
      - ./joomla:/app
      - ./apache-php-lamp/vhost-apache.conf:/etc/apache2/sites-enabled/vhost-apache.conf
      - ./apache-php-lamp/php.ini:/etc/php/8.2/apache2/php.ini
      - ./certs:/certs
    networks:
      redelamplemp:
        aliases:
          - joomla.lan
          - www.joomla.lan
  basededatos:
    image: mysql:latest
    env_file:
        - .env.dev
      #Configuracion da BD de desenrolo
      
    volumes:
      - datos:/var/lib/mysql
    networks:
      redelamplemp:
  #phpmuadmin se se necesita
  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix  
volumes:
  datos:
networks:
  redelamplemp: